### ISSUE TITLE
A way to configure the DB with env vars.

### ISSUE THREAD

**Issue by miller-joe** [linuxserver/docker-pydio-cells#9]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
The team at TrueCharts is willing to integrate this docker for TrueNAS Scale via the TrueCharts project. In fact, it is already done as-is. But, it's non-function due to lack of a database installed. And there is not currently a database app through TrueCharts to use instead.

The TrueCharts team is willing to implement a database into the app. But, database env vars are needed to do this (instead of entering the variables in the setup wizard).

Is this possible to add?

## Current Behavior
Currently, the database credentials are entered for this app through a GUI wizard at first start.

## Alternatives Considered
In order to integrate a built in database install for TrueNAS Scale App a database credential config file is needed that can bypass or autopopulate the GUI wizard fields.

**Comment by tobbenb** [comment]
The web wizard comes from pydio cells and not us, so I don't see us trying to find a way around it as a good solution.

I don't know how true as scale works, but I don't see why a lack of env variables to connect to a database is a show stopper?
It almost sounds like you want there to be MySQL/mariadb installed in the container?

**Comment by miller-joe** [comment]
Ok. Thank you for your consideration. I will ask the Pydio team.

Yes. You are correct that they would install the db at the same time as the app. I'm not 100% sure if "in" the container is technically what they do. But, there are multiple apps that they manage that come with databases set up and running. My understanding is that within the environment they are working in this is easier than maintaining a separate db app.

You can learn more about it here: https://truecharts.org/
